### ISSUE TITLE
關於 [推動由學生團體經營的飲食店] 

### ISSUE THREAD

**Issue by zychen423** [voteping/policy#2]
嗨您好：
1. 關於推動由學生團體經營的飲食店：
   想請問一下您是否有雨有潛在動機參與經營飲食店的社團接洽，詢問他們的動機呢？
   再者想問您想將此飲食店設立在哪？有適合的場地？學校與店家的合約會在你的任期內剛好有空出來的？
   再來，那麼該飲食店會有退場機制嗎？如果沒人買或業績不高是不是該換家？需要需要付錢給學校？
   最後，你自己覺得這項提案在你的任期內開始實施的機率有多高？如果是找社團好了是不是還要先取得你說的執照？然後在開始營業？

謝謝您的耐心看過我的問題

**Comment by voteping** [comment]
抱歉隔了一天才回。關於您的問題，首先，學生會推動的是開店前的基礎建設，像是要求校方開放學生申請/考取校內執業所需的工作證，修改規章讓學生開店只需較低的資本額門檻/較低的權利金等。這些鋪路的過程走完之後，我們當然可以接洽相關(飲料、甜點、輕食類)社團，討論看是共同經營或各自申請。

場地的部分希望是“店面”，不過推動初期或許會先以攤販(類似各大xx週，但長期)的形式。推動學生開店主要是希望能讓學生有更多發揮才能的場域，當然還是要符合相關的開店、食品安全規範。至於退場機制，申請可以以月/學期為單位，表現不佳或違規的團隊會被汰換是一定的，就算表現良好，也會讓不同團隊輪流參與，提供更豐富多元的服務。
